/**
 * Generates the .avif/.webp siblings <Img> serves, plus the manifest it reads
 * to know which widths exist. Run with `bun run images` after adding a raster
 * to public/img/ — it skips anything already newer than its source.
 *
 * Originals stay put: they are the <img> fallback and the only path the
 * sections reference by name.
 */
import sharp, { type Sharp } from "sharp";
import { mkdir, readdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";

const IMG_DIR = new URL("../public/img/", import.meta.url).pathname;
const MANIFEST = new URL("../src/generated/img-widths.ts", import.meta.url)
  .pathname;

/** Ladder covers 1x mobile through 2x desktop; nothing is ever upscaled. */
const LADDER = [480, 960, 1440, 1920];
const MAX_WIDTH = 2400;
const FORMATS = {
  avif: (p: Sharp) => p.avif({ quality: 55, effort: 4 }),
  webp: (p: Sharp) => p.webp({ quality: 78 }),
} as const;

const RASTER = /\.(png|jpe?g)$/i;
const VARIANT = /-\d+\.(avif|webp)$/i;

const mtime = (p: string) =>
  stat(p).then(
    (s) => s.mtimeMs,
    () => 0,
  );

async function variantsFor(file: string) {
  const src = join(IMG_DIR, file);
  const meta = await sharp(src).metadata();
  const intrinsic = Math.min(meta.width ?? 0, MAX_WIDTH);
  if (!intrinsic) throw new Error(`no width for ${file}`);

  // Only widths below the source are worth a resize; the source width itself is
  // always the top candidate so the largest slot still gets a modern format.
  const widths = [...new Set([...LADDER.filter((w) => w < intrinsic), intrinsic])];
  const base = file.replace(RASTER, "");
  const srcTime = await mtime(src);
  let written = 0;

  for (const width of widths) {
    for (const [ext, encode] of Object.entries(FORMATS)) {
      const out = join(IMG_DIR, `${base}-${width}.${ext}`);
      if ((await mtime(out)) > srcTime) continue;
      await encode(sharp(src).resize({ width, withoutEnlargement: true })).toFile(
        out,
      );
      written++;
    }
  }
  return { widths, written };
}

const files = (await readdir(IMG_DIR))
  .filter((f) => RASTER.test(f) && !VARIANT.test(f))
  .sort();

const manifest: Record<string, number[]> = {};
let written = 0;

// ponytail: 6 at a time keeps every core busy without 85 sharp pipelines at once
for (let i = 0; i < files.length; i += 6) {
  const batch = files.slice(i, i + 6);
  const done = await Promise.all(batch.map(variantsFor));
  batch.forEach((file, n) => {
    manifest[`/img/${file}`] = done[n]!.widths;
    written += done[n]!.written;
  });
  console.log(`  ${Math.min(i + 6, files.length)}/${files.length}`);
}

await mkdir(new URL("../src/generated/", import.meta.url).pathname, {
  recursive: true,
});
await writeFile(
  MANIFEST,
  `// Generated by scripts/optimize-images.ts — do not edit.\n` +
    `export const imgWidths: Record<string, number[]> = ${JSON.stringify(
      manifest,
      null,
      2,
    )};\n`,
);

// The manifest is what keeps <source> off a 404, so prove every entry landed.
for (const [src, widths] of Object.entries(manifest)) {
  for (const width of widths) {
    for (const ext of Object.keys(FORMATS)) {
      const p = join(IMG_DIR, `${src.slice(5).replace(RASTER, "")}-${width}.${ext}`);
      if (!(await mtime(p))) throw new Error(`manifest promises a missing ${p}`);
    }
  }
}

console.log(
  `${files.length} sources, ${written} files written, ${Object.values(manifest).flat().length * 2} variants total`,
);
